source "$OUTPOST_INSTALL/preflight/os.sh"
source "$OUTPOST_INSTALL/preflight/gum.sh"
source "$OUTPOST_INSTALL/preflight/firecracker.sh"
source "$OUTPOST_INSTALL/preflight/arch-image.sh"
source "$OUTPOST_INSTALL/preflight/network.sh"
