//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ArkDesiredState.
const (
	ArkDesiredStateDeleted ArkDesiredState = "deleted"
	ArkDesiredStateRunning ArkDesiredState = "running"
	ArkDesiredStateStopped ArkDesiredState = "stopped"
)

// Valid indicates whether the value is a known member of the ArkDesiredState enum.
func (e ArkDesiredState) Valid() bool {
	switch e {
	case ArkDesiredStateDeleted:
		return true
	case ArkDesiredStateRunning:
		return true
	case ArkDesiredStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for ArkStatus.
const (
	ArkStatusDeleting     ArkStatus = "deleting"
	ArkStatusFailed       ArkStatus = "failed"
	ArkStatusProvisioning ArkStatus = "provisioning"
	ArkStatusRunning      ArkStatus = "running"
	ArkStatusStopped      ArkStatus = "stopped"
	ArkStatusStopping     ArkStatus = "stopping"
)

// Valid indicates whether the value is a known member of the ArkStatus enum.
func (e ArkStatus) Valid() bool {
	switch e {
	case ArkStatusDeleting:
		return true
	case ArkStatusFailed:
		return true
	case ArkStatusProvisioning:
		return true
	case ArkStatusRunning:
		return true
	case ArkStatusStopped:
		return true
	case ArkStatusStopping:
		return true
	default:
		return false
	}
}

// Ark defines model for Ark.
type Ark struct {
	CreatedAt    time.Time       `json:"created_at"`
	DesiredState ArkDesiredState `json:"desired_state"`

	// DiskGib Example: 8
	DiskGib int    `json:"disk_gib"`
	Failure string `json:"failure"`
	GuestIp string `json:"guest_ip"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id string `json:"id"`

	// ImageId Example: default
	ImageId string `json:"image_id"`

	// MemoryMib Example: 4096
	MemoryMib int `json:"memory_mib"`

	// Name Example: investigate-deploy
	Name      string    `json:"name"`
	Status    ArkStatus `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`

	// Vcpus Example: 2
	Vcpus int `json:"vcpus"`
}

// ArkDesiredState defines model for Ark.DesiredState.
type ArkDesiredState string

// ArkStatus defines model for Ark.Status.
type ArkStatus string

// CreateArkRequest defines model for CreateArkRequest.
type CreateArkRequest struct {
	// DiskGib Example: 8
	DiskGib int `json:"disk_gib"`

	// ImageId Example: default
	ImageId string `json:"image_id"`

	// MemoryMib Example: 4096
	MemoryMib int `json:"memory_mib"`

	// Name Example: investigate-deploy
	Name string `json:"name"`

	// Vcpus Example: 2
	Vcpus int `json:"vcpus"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// ArkName defines model for ArkName.
type ArkName = string

// Conflict defines model for Conflict.
type Conflict = Error

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServerError defines model for ServerError.
type ServerError = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateArkJSONRequestBody defines body for CreateArk for application/json ContentType.
type CreateArkJSONRequestBody = CreateArkRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListArks List Arks
	//
	// Corresponds with GET /v1/arks (the `ListArks` operationId).
	ListArks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateArkWithBody Create an Ark
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/arks (the `CreateArk` operationId).
	CreateArkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateArk Create an Ark
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/arks (the `CreateArk` operationId).
	CreateArk(ctx context.Context, body CreateArkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteArk Delete an Ark
	//
	// Corresponds with DELETE /v1/arks/{name} (the `DeleteArk` operationId).
	DeleteArk(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetArk Get an Ark
	//
	// Corresponds with GET /v1/arks/{name} (the `GetArk` operationId).
	GetArk(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartArk Start an Ark
	//
	// Corresponds with POST /v1/arks/{name}/start (the `StartArk` operationId).
	StartArk(ctx context.Context, name ArkName, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StopArk Stop an Ark
	//
	// Corresponds with POST /v1/arks/{name}/stop (the `StopArk` operationId).
	StopArk(ctx context.Context, name ArkName, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListArks List Arks
//
// Corresponds with GET /v1/arks (the `ListArks` operationId).
func (c *Client) ListArks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListArksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateArkWithBody Create an Ark
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/arks (the `CreateArk` operationId).
func (c *Client) CreateArkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateArkRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateArk Create an Ark
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/arks (the `CreateArk` operationId).
func (c *Client) CreateArk(ctx context.Context, body CreateArkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateArkRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteArk Delete an Ark
//
// Corresponds with DELETE /v1/arks/{name} (the `DeleteArk` operationId).
func (c *Client) DeleteArk(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteArkRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetArk Get an Ark
//
// Corresponds with GET /v1/arks/{name} (the `GetArk` operationId).
func (c *Client) GetArk(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetArkRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// StartArk Start an Ark
//
// Corresponds with POST /v1/arks/{name}/start (the `StartArk` operationId).
func (c *Client) StartArk(ctx context.Context, name ArkName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartArkRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// StopArk Stop an Ark
//
// Corresponds with POST /v1/arks/{name}/stop (the `StopArk` operationId).
func (c *Client) StopArk(ctx context.Context, name ArkName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStopArkRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListArksRequest constructs an http.Request for the ListArks method
func NewListArksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/arks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateArkRequest calls the generic CreateArk builder with application/json body
func NewCreateArkRequest(server string, body CreateArkJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateArkRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateArkRequestWithBody constructs an http.Request for the CreateArk method, with any body, and a specified content type
func NewCreateArkRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/arks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteArkRequest constructs an http.Request for the DeleteArk method
func NewDeleteArkRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/arks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetArkRequest constructs an http.Request for the GetArk method
func NewGetArkRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/arks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartArkRequest constructs an http.Request for the StartArk method
func NewStartArkRequest(server string, name ArkName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/arks/%s/start", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStopArkRequest constructs an http.Request for the StopArk method
func NewStopArkRequest(server string, name ArkName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/arks/%s/stop", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListArksWithResponse List Arks
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/arks (the `ListArks` operationId).
	ListArksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListArksResponse, error)

	// CreateArkWithBodyWithResponse Create an Ark
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/arks (the `CreateArk` operationId).
	CreateArkWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateArkResponse, error)

	// CreateArkWithResponse Create an Ark
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/arks (the `CreateArk` operationId).
	CreateArkWithResponse(ctx context.Context, body CreateArkJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateArkResponse, error)

	// DeleteArkWithResponse Delete an Ark
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /v1/arks/{name} (the `DeleteArk` operationId).
	DeleteArkWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*DeleteArkResponse, error)

	// GetArkWithResponse Get an Ark
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/arks/{name} (the `GetArk` operationId).
	GetArkWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetArkResponse, error)

	// StartArkWithResponse Start an Ark
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/arks/{name}/start (the `StartArk` operationId).
	StartArkWithResponse(ctx context.Context, name ArkName, reqEditors ...RequestEditorFn) (*StartArkResponse, error)

	// StopArkWithResponse Stop an Ark
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/arks/{name}/stop (the `StopArk` operationId).
	StopArkWithResponse(ctx context.Context, name ArkName, reqEditors ...RequestEditorFn) (*StopArkResponse, error)
}

type ListArksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Ark
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListArksResponse) GetJSON200() *[]Ark {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListArksResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListArksResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ListArksResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListArksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListArksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListArksResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateArkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Ark
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateArkResponse) GetJSON201() *Ark {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateArkResponse) GetJSON400() *InvalidRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreateArkResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateArkResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreateArkResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r CreateArkResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateArkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateArkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateArkResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteArkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Ark
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DeleteArkResponse) GetJSON200() *Ark {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DeleteArkResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteArkResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteArkResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r DeleteArkResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r DeleteArkResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteArkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteArkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteArkResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetArkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Ark
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetArkResponse) GetJSON200() *Ark {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetArkResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetArkResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetArkResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetArkResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetArkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetArkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetArkResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StartArkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Ark
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r StartArkResponse) GetJSON200() *Ark {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r StartArkResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r StartArkResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r StartArkResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r StartArkResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r StartArkResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r StartArkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartArkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StartArkResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StopArkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Ark
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r StopArkResponse) GetJSON200() *Ark {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r StopArkResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r StopArkResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r StopArkResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r StopArkResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r StopArkResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r StopArkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StopArkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StopArkResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListArksWithResponse List Arks
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/arks (the `ListArks` operationId).
func (c *ClientWithResponses) ListArksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListArksResponse, error) {
	rsp, err := c.ListArks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListArksResponse(rsp)
}

// CreateArkWithBodyWithResponse Create an Ark
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/arks (the `CreateArk` operationId).
func (c *ClientWithResponses) CreateArkWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateArkResponse, error) {
	rsp, err := c.CreateArkWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateArkResponse(rsp)
}

// CreateArkWithResponse Create an Ark
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/arks (the `CreateArk` operationId).
func (c *ClientWithResponses) CreateArkWithResponse(ctx context.Context, body CreateArkJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateArkResponse, error) {
	rsp, err := c.CreateArk(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateArkResponse(rsp)
}

// DeleteArkWithResponse Delete an Ark
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /v1/arks/{name} (the `DeleteArk` operationId).
func (c *ClientWithResponses) DeleteArkWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*DeleteArkResponse, error) {
	rsp, err := c.DeleteArk(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteArkResponse(rsp)
}

// GetArkWithResponse Get an Ark
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/arks/{name} (the `GetArk` operationId).
func (c *ClientWithResponses) GetArkWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetArkResponse, error) {
	rsp, err := c.GetArk(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetArkResponse(rsp)
}

// StartArkWithResponse Start an Ark
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/arks/{name}/start (the `StartArk` operationId).
func (c *ClientWithResponses) StartArkWithResponse(ctx context.Context, name ArkName, reqEditors ...RequestEditorFn) (*StartArkResponse, error) {
	rsp, err := c.StartArk(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartArkResponse(rsp)
}

// StopArkWithResponse Stop an Ark
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/arks/{name}/stop (the `StopArk` operationId).
func (c *ClientWithResponses) StopArkWithResponse(ctx context.Context, name ArkName, reqEditors ...RequestEditorFn) (*StopArkResponse, error) {
	rsp, err := c.StopArk(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStopArkResponse(rsp)
}

// ParseListArksResponse parses an HTTP response from a ListArksWithResponse call
func ParseListArksResponse(rsp *http.Response) (*ListArksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListArksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Ark
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateArkResponse parses an HTTP response from a CreateArkWithResponse call
func ParseCreateArkResponse(rsp *http.Response) (*CreateArkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateArkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Ark
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteArkResponse parses an HTTP response from a DeleteArkWithResponse call
func ParseDeleteArkResponse(rsp *http.Response) (*DeleteArkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteArkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Ark
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetArkResponse parses an HTTP response from a GetArkWithResponse call
func ParseGetArkResponse(rsp *http.Response) (*GetArkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetArkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Ark
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseStartArkResponse parses an HTTP response from a StartArkWithResponse call
func ParseStartArkResponse(rsp *http.Response) (*StartArkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartArkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Ark
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseStopArkResponse parses an HTTP response from a StopArkWithResponse call
func ParseStopArkResponse(rsp *http.Response) (*StopArkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StopArkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Ark
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListArks List Arks
	// (GET /v1/arks)
	ListArks(w http.ResponseWriter, r *http.Request)
	// CreateArk Create an Ark
	// (POST /v1/arks)
	CreateArk(w http.ResponseWriter, r *http.Request)
	// DeleteArk Delete an Ark
	// (DELETE /v1/arks/{name})
	DeleteArk(w http.ResponseWriter, r *http.Request, name string)
	// GetArk Get an Ark
	// (GET /v1/arks/{name})
	GetArk(w http.ResponseWriter, r *http.Request, name string)
	// StartArk Start an Ark
	// (POST /v1/arks/{name}/start)
	StartArk(w http.ResponseWriter, r *http.Request, name ArkName)
	// StopArk Stop an Ark
	// (POST /v1/arks/{name}/stop)
	StopArk(w http.ResponseWriter, r *http.Request, name ArkName)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListArks operation middleware
func (siw *ServerInterfaceWrapper) ListArks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateArk operation middleware
func (siw *ServerInterfaceWrapper) CreateArk(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateArk(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArk operation middleware
func (siw *ServerInterfaceWrapper) DeleteArk(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArk(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArk operation middleware
func (siw *ServerInterfaceWrapper) GetArk(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArk(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartArk operation middleware
func (siw *ServerInterfaceWrapper) StartArk(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ArkName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartArk(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopArk operation middleware
func (siw *ServerInterfaceWrapper) StopArk(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name ArkName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopArk(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/arks", wrapper.ListArks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/arks", wrapper.CreateArk)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/arks/{name}", wrapper.DeleteArk)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/arks/{name}", wrapper.GetArk)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/arks/{name}/start", wrapper.StartArk)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/arks/{name}/stop", wrapper.StopArk)

	return m
}
