//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for OutpostDesiredState.
const (
	OutpostDesiredStateDeleted OutpostDesiredState = "deleted"
	OutpostDesiredStateRunning OutpostDesiredState = "running"
	OutpostDesiredStateStopped OutpostDesiredState = "stopped"
)

// Valid indicates whether the value is a known member of the OutpostDesiredState enum.
func (e OutpostDesiredState) Valid() bool {
	switch e {
	case OutpostDesiredStateDeleted:
		return true
	case OutpostDesiredStateRunning:
		return true
	case OutpostDesiredStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for OutpostStatus.
const (
	OutpostStatusDeleting     OutpostStatus = "deleting"
	OutpostStatusFailed       OutpostStatus = "failed"
	OutpostStatusProvisioning OutpostStatus = "provisioning"
	OutpostStatusRunning      OutpostStatus = "running"
	OutpostStatusStopped      OutpostStatus = "stopped"
	OutpostStatusStopping     OutpostStatus = "stopping"
)

// Valid indicates whether the value is a known member of the OutpostStatus enum.
func (e OutpostStatus) Valid() bool {
	switch e {
	case OutpostStatusDeleting:
		return true
	case OutpostStatusFailed:
		return true
	case OutpostStatusProvisioning:
		return true
	case OutpostStatusRunning:
		return true
	case OutpostStatusStopped:
		return true
	case OutpostStatusStopping:
		return true
	default:
		return false
	}
}

// CreateOutpostRequest defines model for CreateOutpostRequest.
type CreateOutpostRequest struct {
	// DiskGib Example: 8
	DiskGib int `json:"disk_gib"`

	// ImageId Example: default
	ImageId string `json:"image_id"`

	// MemoryMib Example: 4096
	MemoryMib int `json:"memory_mib"`

	// Name Example: investigate-deploy
	Name         string  `json:"name"`
	SshPublicKey *string `json:"ssh_public_key,omitempty"`

	// Vcpus Example: 2
	Vcpus int `json:"vcpus"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Image defines model for Image.
type Image struct {
	CreatedAt time.Time `json:"created_at"`
	Digest    string    `json:"digest"`
	SizeBytes int       `json:"size_bytes"`
	Tags      []string  `json:"tags"`
}

// Outpost defines model for Outpost.
type Outpost struct {
	CreatedAt    time.Time           `json:"created_at"`
	DesiredState OutpostDesiredState `json:"desired_state"`

	// DiskGib Example: 8
	DiskGib int    `json:"disk_gib"`
	Failure string `json:"failure"`
	GuestIp string `json:"guest_ip"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id string `json:"id"`

	// ImageId Example: default
	ImageId string `json:"image_id"`

	// MemoryMib Example: 4096
	MemoryMib int `json:"memory_mib"`

	// Name Example: investigate-deploy
	Name      string        `json:"name"`
	Status    OutpostStatus `json:"status"`
	UpdatedAt time.Time     `json:"updated_at"`

	// Vcpus Example: 2
	Vcpus int `json:"vcpus"`
}

// OutpostDesiredState defines model for Outpost.DesiredState.
type OutpostDesiredState string

// OutpostStatus defines model for Outpost.Status.
type OutpostStatus string

// OutpostName defines model for OutpostName.
type OutpostName = string

// Conflict defines model for Conflict.
type Conflict = Error

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServerError defines model for ServerError.
type ServerError = Error

// TooLarge defines model for TooLarge.
type TooLarge = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unavailable defines model for Unavailable.
type Unavailable = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// ImportImageParams defines parameters for ImportImage.
type ImportImageParams struct {
	Tag string `form:"tag" json:"tag"`
}

// BuildImageParams defines parameters for BuildImage.
type BuildImageParams struct {
	Tag string `form:"tag" json:"tag"`
}

// CreateOutpostJSONRequestBody defines body for CreateOutpost for application/json ContentType.
type CreateOutpostJSONRequestBody = CreateOutpostRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListImages performs a GET /v1/images (the `ListImages` operationId) request.
	ListImages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ImportImageWithBody performs a POST /v1/images (the `ImportImage` operationId) request,
	// with any type of body and a specified content type.
	ImportImageWithBody(ctx context.Context, params *ImportImageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BuildImageWithBody performs a POST /v1/images/build (the `BuildImage` operationId) request,
	// with any type of body and a specified content type.
	BuildImageWithBody(ctx context.Context, params *BuildImageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GcImages performs a POST /v1/images/gc (the `GcImages` operationId) request.
	GcImages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteImage performs a DELETE /v1/images/{reference} (the `DeleteImage` operationId) request.
	DeleteImage(ctx context.Context, reference string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetImage performs a GET /v1/images/{reference} (the `GetImage` operationId) request.
	GetImage(ctx context.Context, reference string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListOutposts List Outposts
	//
	// Corresponds with GET /v1/outposts (the `ListOutposts` operationId).
	ListOutposts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateOutpostWithBody Create an Outpost
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/outposts (the `CreateOutpost` operationId).
	CreateOutpostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateOutpost Create an Outpost
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/outposts (the `CreateOutpost` operationId).
	CreateOutpost(ctx context.Context, body CreateOutpostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteOutpost Delete an Outpost
	//
	// Corresponds with DELETE /v1/outposts/{name} (the `DeleteOutpost` operationId).
	DeleteOutpost(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOutpost Get an Outpost
	//
	// Corresponds with GET /v1/outposts/{name} (the `GetOutpost` operationId).
	GetOutpost(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartOutpost Start an Outpost
	//
	// Corresponds with POST /v1/outposts/{name}/start (the `StartOutpost` operationId).
	StartOutpost(ctx context.Context, name OutpostName, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StopOutpost Stop an Outpost
	//
	// Corresponds with POST /v1/outposts/{name}/stop (the `StopOutpost` operationId).
	StopOutpost(ctx context.Context, name OutpostName, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListImages performs a GET /v1/images (the `ListImages` operationId) request.
func (c *Client) ListImages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListImagesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ImportImageWithBody performs a POST /v1/images (the `ImportImage` operationId) request,
// with any type of body and a specified content type.
func (c *Client) ImportImageWithBody(ctx context.Context, params *ImportImageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewImportImageRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// BuildImageWithBody performs a POST /v1/images/build (the `BuildImage` operationId) request,
// with any type of body and a specified content type.
func (c *Client) BuildImageWithBody(ctx context.Context, params *BuildImageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBuildImageRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GcImages performs a POST /v1/images/gc (the `GcImages` operationId) request.
func (c *Client) GcImages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGcImagesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteImage performs a DELETE /v1/images/{reference} (the `DeleteImage` operationId) request.
func (c *Client) DeleteImage(ctx context.Context, reference string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteImageRequest(c.Server, reference)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetImage performs a GET /v1/images/{reference} (the `GetImage` operationId) request.
func (c *Client) GetImage(ctx context.Context, reference string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetImageRequest(c.Server, reference)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListOutposts List Outposts
//
// Corresponds with GET /v1/outposts (the `ListOutposts` operationId).
func (c *Client) ListOutposts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListOutpostsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateOutpostWithBody Create an Outpost
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/outposts (the `CreateOutpost` operationId).
func (c *Client) CreateOutpostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOutpostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateOutpost Create an Outpost
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/outposts (the `CreateOutpost` operationId).
func (c *Client) CreateOutpost(ctx context.Context, body CreateOutpostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOutpostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteOutpost Delete an Outpost
//
// Corresponds with DELETE /v1/outposts/{name} (the `DeleteOutpost` operationId).
func (c *Client) DeleteOutpost(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteOutpostRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetOutpost Get an Outpost
//
// Corresponds with GET /v1/outposts/{name} (the `GetOutpost` operationId).
func (c *Client) GetOutpost(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOutpostRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// StartOutpost Start an Outpost
//
// Corresponds with POST /v1/outposts/{name}/start (the `StartOutpost` operationId).
func (c *Client) StartOutpost(ctx context.Context, name OutpostName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartOutpostRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// StopOutpost Stop an Outpost
//
// Corresponds with POST /v1/outposts/{name}/stop (the `StopOutpost` operationId).
func (c *Client) StopOutpost(ctx context.Context, name OutpostName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStopOutpostRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListImagesRequest constructs an http.Request for the ListImages method
func NewListImagesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/images")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewImportImageRequestWithBody constructs an http.Request for the ImportImage method, with any body, and a specified content type
func NewImportImageRequestWithBody(server string, params *ImportImageParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/images")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tag", params.Tag, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewBuildImageRequestWithBody constructs an http.Request for the BuildImage method, with any body, and a specified content type
func NewBuildImageRequestWithBody(server string, params *BuildImageParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/images/build")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tag", params.Tag, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGcImagesRequest constructs an http.Request for the GcImages method
func NewGcImagesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/images/gc")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteImageRequest constructs an http.Request for the DeleteImage method
func NewDeleteImageRequest(server string, reference string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "reference", reference, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/images/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetImageRequest constructs an http.Request for the GetImage method
func NewGetImageRequest(server string, reference string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "reference", reference, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/images/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListOutpostsRequest constructs an http.Request for the ListOutposts method
func NewListOutpostsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/outposts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateOutpostRequest calls the generic CreateOutpost builder with application/json body
func NewCreateOutpostRequest(server string, body CreateOutpostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOutpostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateOutpostRequestWithBody constructs an http.Request for the CreateOutpost method, with any body, and a specified content type
func NewCreateOutpostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/outposts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteOutpostRequest constructs an http.Request for the DeleteOutpost method
func NewDeleteOutpostRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/outposts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetOutpostRequest constructs an http.Request for the GetOutpost method
func NewGetOutpostRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/outposts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartOutpostRequest constructs an http.Request for the StartOutpost method
func NewStartOutpostRequest(server string, name OutpostName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/outposts/%s/start", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStopOutpostRequest constructs an http.Request for the StopOutpost method
func NewStopOutpostRequest(server string, name OutpostName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/outposts/%s/stop", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListImagesWithResponse performs a GET /v1/images (the `ListImages` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	ListImagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListImagesResponse, error)

	// ImportImageWithBodyWithResponse performs a POST /v1/images (the `ImportImage` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	ImportImageWithBodyWithResponse(ctx context.Context, params *ImportImageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ImportImageResponse, error)

	// BuildImageWithBodyWithResponse performs a POST /v1/images/build (the `BuildImage` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	BuildImageWithBodyWithResponse(ctx context.Context, params *BuildImageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BuildImageResponse, error)

	// GcImagesWithResponse performs a POST /v1/images/gc (the `GcImages` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GcImagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GcImagesResponse, error)

	// DeleteImageWithResponse performs a DELETE /v1/images/{reference} (the `DeleteImage` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	DeleteImageWithResponse(ctx context.Context, reference string, reqEditors ...RequestEditorFn) (*DeleteImageResponse, error)

	// GetImageWithResponse performs a GET /v1/images/{reference} (the `GetImage` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetImageWithResponse(ctx context.Context, reference string, reqEditors ...RequestEditorFn) (*GetImageResponse, error)

	// ListOutpostsWithResponse List Outposts
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/outposts (the `ListOutposts` operationId).
	ListOutpostsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListOutpostsResponse, error)

	// CreateOutpostWithBodyWithResponse Create an Outpost
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/outposts (the `CreateOutpost` operationId).
	CreateOutpostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOutpostResponse, error)

	// CreateOutpostWithResponse Create an Outpost
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/outposts (the `CreateOutpost` operationId).
	CreateOutpostWithResponse(ctx context.Context, body CreateOutpostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOutpostResponse, error)

	// DeleteOutpostWithResponse Delete an Outpost
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /v1/outposts/{name} (the `DeleteOutpost` operationId).
	DeleteOutpostWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*DeleteOutpostResponse, error)

	// GetOutpostWithResponse Get an Outpost
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/outposts/{name} (the `GetOutpost` operationId).
	GetOutpostWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetOutpostResponse, error)

	// StartOutpostWithResponse Start an Outpost
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/outposts/{name}/start (the `StartOutpost` operationId).
	StartOutpostWithResponse(ctx context.Context, name OutpostName, reqEditors ...RequestEditorFn) (*StartOutpostResponse, error)

	// StopOutpostWithResponse Stop an Outpost
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/outposts/{name}/stop (the `StopOutpost` operationId).
	StopOutpostWithResponse(ctx context.Context, name OutpostName, reqEditors ...RequestEditorFn) (*StopOutpostResponse, error)
}

type ListImagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Image
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Unavailable
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListImagesResponse) GetJSON200() *[]Image {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListImagesResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListImagesResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r ListImagesResponse) GetJSON503() *Unavailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r ListImagesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListImagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ImportImageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Image
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *TooLarge
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *UnsupportedMediaType
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Unavailable
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r ImportImageResponse) GetJSON201() *Image {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ImportImageResponse) GetJSON400() *InvalidRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ImportImageResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r ImportImageResponse) GetJSON413() *TooLarge {
	return r.JSON413
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r ImportImageResponse) GetJSON415() *UnsupportedMediaType {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ImportImageResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r ImportImageResponse) GetJSON503() *Unavailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r ImportImageResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ImportImageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ImportImageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ImportImageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type BuildImageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Image
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *TooLarge
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *UnsupportedMediaType
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Unavailable
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r BuildImageResponse) GetJSON201() *Image {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r BuildImageResponse) GetJSON400() *InvalidRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r BuildImageResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r BuildImageResponse) GetJSON413() *TooLarge {
	return r.JSON413
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r BuildImageResponse) GetJSON415() *UnsupportedMediaType {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r BuildImageResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r BuildImageResponse) GetJSON503() *Unavailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r BuildImageResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BuildImageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BuildImageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BuildImageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GcImagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]string
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Unavailable
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GcImagesResponse) GetJSON200() *[]string {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GcImagesResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GcImagesResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r GcImagesResponse) GetJSON503() *Unavailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r GcImagesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GcImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GcImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GcImagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteImageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Unavailable
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DeleteImageResponse) GetJSON400() *InvalidRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DeleteImageResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteImageResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteImageResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r DeleteImageResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r DeleteImageResponse) GetJSON503() *Unavailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r DeleteImageResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteImageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteImageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteImageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetImageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Image
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Unavailable
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetImageResponse) GetJSON200() *Image {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetImageResponse) GetJSON400() *InvalidRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetImageResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetImageResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetImageResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r GetImageResponse) GetJSON503() *Unavailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r GetImageResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetImageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetImageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetImageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListOutpostsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Outpost
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListOutpostsResponse) GetJSON200() *[]Outpost {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListOutpostsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListOutpostsResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ListOutpostsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListOutpostsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListOutpostsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListOutpostsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateOutpostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Outpost
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateOutpostResponse) GetJSON201() *Outpost {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateOutpostResponse) GetJSON400() *InvalidRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreateOutpostResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateOutpostResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreateOutpostResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r CreateOutpostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateOutpostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateOutpostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateOutpostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteOutpostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Outpost
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DeleteOutpostResponse) GetJSON200() *Outpost {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DeleteOutpostResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteOutpostResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteOutpostResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r DeleteOutpostResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r DeleteOutpostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteOutpostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteOutpostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteOutpostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetOutpostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Outpost
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetOutpostResponse) GetJSON200() *Outpost {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetOutpostResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetOutpostResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetOutpostResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetOutpostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetOutpostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOutpostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOutpostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StartOutpostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Outpost
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r StartOutpostResponse) GetJSON200() *Outpost {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r StartOutpostResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r StartOutpostResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r StartOutpostResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r StartOutpostResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r StartOutpostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r StartOutpostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartOutpostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StartOutpostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StopOutpostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Outpost
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r StopOutpostResponse) GetJSON200() *Outpost {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r StopOutpostResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r StopOutpostResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r StopOutpostResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r StopOutpostResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r StopOutpostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r StopOutpostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StopOutpostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StopOutpostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListImagesWithResponse performs a GET /v1/images (the `ListImages` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ListImagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListImagesResponse, error) {
	rsp, err := c.ListImages(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListImagesResponse(rsp)
}

// ImportImageWithBodyWithResponse performs a POST /v1/images (the `ImportImage` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ImportImageWithBodyWithResponse(ctx context.Context, params *ImportImageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ImportImageResponse, error) {
	rsp, err := c.ImportImageWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseImportImageResponse(rsp)
}

// BuildImageWithBodyWithResponse performs a POST /v1/images/build (the `BuildImage` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) BuildImageWithBodyWithResponse(ctx context.Context, params *BuildImageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BuildImageResponse, error) {
	rsp, err := c.BuildImageWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBuildImageResponse(rsp)
}

// GcImagesWithResponse performs a POST /v1/images/gc (the `GcImages` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GcImagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GcImagesResponse, error) {
	rsp, err := c.GcImages(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGcImagesResponse(rsp)
}

// DeleteImageWithResponse performs a DELETE /v1/images/{reference} (the `DeleteImage` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DeleteImageWithResponse(ctx context.Context, reference string, reqEditors ...RequestEditorFn) (*DeleteImageResponse, error) {
	rsp, err := c.DeleteImage(ctx, reference, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteImageResponse(rsp)
}

// GetImageWithResponse performs a GET /v1/images/{reference} (the `GetImage` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetImageWithResponse(ctx context.Context, reference string, reqEditors ...RequestEditorFn) (*GetImageResponse, error) {
	rsp, err := c.GetImage(ctx, reference, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetImageResponse(rsp)
}

// ListOutpostsWithResponse List Outposts
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/outposts (the `ListOutposts` operationId).
func (c *ClientWithResponses) ListOutpostsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListOutpostsResponse, error) {
	rsp, err := c.ListOutposts(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListOutpostsResponse(rsp)
}

// CreateOutpostWithBodyWithResponse Create an Outpost
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/outposts (the `CreateOutpost` operationId).
func (c *ClientWithResponses) CreateOutpostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOutpostResponse, error) {
	rsp, err := c.CreateOutpostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOutpostResponse(rsp)
}

// CreateOutpostWithResponse Create an Outpost
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/outposts (the `CreateOutpost` operationId).
func (c *ClientWithResponses) CreateOutpostWithResponse(ctx context.Context, body CreateOutpostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOutpostResponse, error) {
	rsp, err := c.CreateOutpost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOutpostResponse(rsp)
}

// DeleteOutpostWithResponse Delete an Outpost
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /v1/outposts/{name} (the `DeleteOutpost` operationId).
func (c *ClientWithResponses) DeleteOutpostWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*DeleteOutpostResponse, error) {
	rsp, err := c.DeleteOutpost(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteOutpostResponse(rsp)
}

// GetOutpostWithResponse Get an Outpost
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/outposts/{name} (the `GetOutpost` operationId).
func (c *ClientWithResponses) GetOutpostWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetOutpostResponse, error) {
	rsp, err := c.GetOutpost(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOutpostResponse(rsp)
}

// StartOutpostWithResponse Start an Outpost
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/outposts/{name}/start (the `StartOutpost` operationId).
func (c *ClientWithResponses) StartOutpostWithResponse(ctx context.Context, name OutpostName, reqEditors ...RequestEditorFn) (*StartOutpostResponse, error) {
	rsp, err := c.StartOutpost(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartOutpostResponse(rsp)
}

// StopOutpostWithResponse Stop an Outpost
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/outposts/{name}/stop (the `StopOutpost` operationId).
func (c *ClientWithResponses) StopOutpostWithResponse(ctx context.Context, name OutpostName, reqEditors ...RequestEditorFn) (*StopOutpostResponse, error) {
	rsp, err := c.StopOutpost(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStopOutpostResponse(rsp)
}

// ParseListImagesResponse parses an HTTP response from a ListImagesWithResponse call
func ParseListImagesResponse(rsp *http.Response) (*ListImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Image
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Unavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseImportImageResponse parses an HTTP response from a ImportImageWithResponse call
func ParseImportImageResponse(rsp *http.Response) (*ImportImageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ImportImageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Image
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest TooLarge
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest UnsupportedMediaType
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Unavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseBuildImageResponse parses an HTTP response from a BuildImageWithResponse call
func ParseBuildImageResponse(rsp *http.Response) (*BuildImageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BuildImageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Image
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest TooLarge
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest UnsupportedMediaType
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Unavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGcImagesResponse parses an HTTP response from a GcImagesWithResponse call
func ParseGcImagesResponse(rsp *http.Response) (*GcImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GcImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Unavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseDeleteImageResponse parses an HTTP response from a DeleteImageWithResponse call
func ParseDeleteImageResponse(rsp *http.Response) (*DeleteImageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteImageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Unavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetImageResponse parses an HTTP response from a GetImageWithResponse call
func ParseGetImageResponse(rsp *http.Response) (*GetImageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetImageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Image
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Unavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseListOutpostsResponse parses an HTTP response from a ListOutpostsWithResponse call
func ParseListOutpostsResponse(rsp *http.Response) (*ListOutpostsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListOutpostsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Outpost
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateOutpostResponse parses an HTTP response from a CreateOutpostWithResponse call
func ParseCreateOutpostResponse(rsp *http.Response) (*CreateOutpostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateOutpostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Outpost
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteOutpostResponse parses an HTTP response from a DeleteOutpostWithResponse call
func ParseDeleteOutpostResponse(rsp *http.Response) (*DeleteOutpostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteOutpostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Outpost
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetOutpostResponse parses an HTTP response from a GetOutpostWithResponse call
func ParseGetOutpostResponse(rsp *http.Response) (*GetOutpostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOutpostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Outpost
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseStartOutpostResponse parses an HTTP response from a StartOutpostWithResponse call
func ParseStartOutpostResponse(rsp *http.Response) (*StartOutpostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartOutpostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Outpost
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseStopOutpostResponse parses an HTTP response from a StopOutpostWithResponse call
func ParseStopOutpostResponse(rsp *http.Response) (*StopOutpostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StopOutpostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Outpost
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/images)
	ListImages(w http.ResponseWriter, r *http.Request)

	// (POST /v1/images)
	ImportImage(w http.ResponseWriter, r *http.Request, params ImportImageParams)

	// (POST /v1/images/build)
	BuildImage(w http.ResponseWriter, r *http.Request, params BuildImageParams)

	// (POST /v1/images/gc)
	GcImages(w http.ResponseWriter, r *http.Request)

	// (DELETE /v1/images/{reference})
	DeleteImage(w http.ResponseWriter, r *http.Request, reference string)

	// (GET /v1/images/{reference})
	GetImage(w http.ResponseWriter, r *http.Request, reference string)
	// ListOutposts List Outposts
	// (GET /v1/outposts)
	ListOutposts(w http.ResponseWriter, r *http.Request)
	// CreateOutpost Create an Outpost
	// (POST /v1/outposts)
	CreateOutpost(w http.ResponseWriter, r *http.Request)
	// DeleteOutpost Delete an Outpost
	// (DELETE /v1/outposts/{name})
	DeleteOutpost(w http.ResponseWriter, r *http.Request, name string)
	// GetOutpost Get an Outpost
	// (GET /v1/outposts/{name})
	GetOutpost(w http.ResponseWriter, r *http.Request, name string)
	// StartOutpost Start an Outpost
	// (POST /v1/outposts/{name}/start)
	StartOutpost(w http.ResponseWriter, r *http.Request, name OutpostName)
	// StopOutpost Stop an Outpost
	// (POST /v1/outposts/{name}/stop)
	StopOutpost(w http.ResponseWriter, r *http.Request, name OutpostName)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListImages operation middleware
func (siw *ServerInterfaceWrapper) ListImages(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListImages(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportImage operation middleware
func (siw *ServerInterfaceWrapper) ImportImage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ImportImageParams

	// ------------- Required query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportImage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BuildImage operation middleware
func (siw *ServerInterfaceWrapper) BuildImage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params BuildImageParams

	// ------------- Required query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BuildImage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GcImages operation middleware
func (siw *ServerInterfaceWrapper) GcImages(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GcImages(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteImage operation middleware
func (siw *ServerInterfaceWrapper) DeleteImage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "reference" -------------
	var reference string

	err = runtime.BindStyledParameterWithOptions("simple", "reference", r.PathValue("reference"), &reference, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reference", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteImage(w, r, reference)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImage operation middleware
func (siw *ServerInterfaceWrapper) GetImage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "reference" -------------
	var reference string

	err = runtime.BindStyledParameterWithOptions("simple", "reference", r.PathValue("reference"), &reference, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reference", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImage(w, r, reference)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOutposts operation middleware
func (siw *ServerInterfaceWrapper) ListOutposts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOutposts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOutpost operation middleware
func (siw *ServerInterfaceWrapper) CreateOutpost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOutpost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOutpost operation middleware
func (siw *ServerInterfaceWrapper) DeleteOutpost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOutpost(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOutpost operation middleware
func (siw *ServerInterfaceWrapper) GetOutpost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOutpost(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartOutpost operation middleware
func (siw *ServerInterfaceWrapper) StartOutpost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name OutpostName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartOutpost(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopOutpost operation middleware
func (siw *ServerInterfaceWrapper) StopOutpost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name OutpostName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopOutpost(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/outposts", wrapper.ListOutposts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/outposts", wrapper.CreateOutpost)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/outposts/{name}", wrapper.DeleteOutpost)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/outposts/{name}", wrapper.GetOutpost)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/outposts/{name}/start", wrapper.StartOutpost)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/outposts/{name}/stop", wrapper.StopOutpost)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/images", wrapper.ListImages)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/images", wrapper.ImportImage)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/images/build", wrapper.BuildImage)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/images/{reference}", wrapper.DeleteImage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/images/{reference}", wrapper.GetImage)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/images/gc", wrapper.GcImages)

	return m
}
